name:                pandoc-sidenote
version:             0.23.0.0
github:              jez/pandoc-sidenote
license:             MIT
license-file:        LICENSE
author:              Jake Zimmerman
maintainer:          zimmerman.jake@gmail.com
copyright:           2016 Jake Zimmerman

flags:
  html-sidenotes:
    description: Enable HTML sidenotes
    default:     False
    manual:      True

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
synopsis:            Convert Pandoc Markdown-style footnotes into sidenotes
description: >
  This is a simple Pandoc filter to convert footnotes into a format that can be
  consumed by Tufte CSS. On the whole, this project weighs in at well under 100
  lines of code. Check out SideNote.hs if you're curious how it works.
category:            CommandLine

ghc-options:
- -Wall
- -Wcompat
- -Wmissing-signatures
- -Werror
- -funbox-strict-fields

dependencies:
- base >= 4.7 && < 5
- mtl
- pandoc-types >= 1.22
- text

library:
  source-dirs: src
  exposed-modules: Text.Pandoc.SideNote
  when:
    - condition: flag(html-sidenotes)
      dependencies: pandoc
      exposed-modules: Text.Pandoc.SideNoteHTML

executables:
  pandoc-sidenote:
    main:                Main.hs
    source-dirs:         ./
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-sidenote
